#numero1 = int(input('Digite um numeor'))
#numero2 = int(input('Digite outro numero'))
#res = int(numero1) + (numero2)
#print('A soma entre {} e {} equivale a {}'.format(numero1, numero2, res))
n =(input('Digite Algo'))
print('{} é esta em letras minusculas ? {}'.format(n,n.islower()))
print('{} é um numero ? {}'.format(n, n.isnumeric()))