nome = input('Digite o nome do aluno')
nota = input('Digite uma nota do aluno')
nota2 = input('Digite a segunda nota')
media = int(nota) + int(nota2)
print('A media do aluno {} e de {}'.format(nome, media))