n = input('Digite seu numero para ver a tabuada')
um = int(n) * 1
dois = int(n) * 2
tres = int(n) * 3
quatro = int(n) * 4
cinco = int(n) * 5
seis = int(n) * 6
sete = int(n) * 7
oito = int(n) * 8
nove = int(n) * 9
dez = int(n) * 10
print('{} * 1 = {}'.format(n, um))
print('{} * 2 = {}'.format(n, dois))
print('{} * 3 = {}'.format(n, tres))
print('{} * 4 = {}'.format(n, quatro))
print('{} * 5 = {}'.format(n, cinco))
print('{} * 6 = {}'.format(n, seis))
print('{} * 7 = {}'.format(n, sete))
print('{} * 8 = {}'.format(n,oito))
print('{} * 9 = {}'.format(n, nove))
print('{} * 10 = {}'.format(n, dez))